name: ${project.name}
main: co.civcraft.attrhider.AttrHider
version: ${project.version}
description: ${project.description}
website: ${project.url}
authors: [Squeenix, Okx]
depend: [ProtocolLib]
api-version: 1.16
